apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: bitcoin
  name: bitcoin
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        service: bitcoin
    spec:
      containers:
      - env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoin
              key: rpcuser
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcoin
              key: rpcpass
        image: gcr.io/bitcoinsv/github-rohenaz-bitcoinsv:c0e64862ade7346cd59c22dfe1c199110e062892
        name: bitcoin
        volumeMounts:
          - mountPath: /bitcoinsv
            name: bitcoinsv
        resources:
          requests:
            memory: "2Gi"
      restartPolicy: Always
      volumes:
        - name: bitcoinsv
          gcePersistentDisk:
            pdName: bitcoinsv
            fsType: ext4
